#ifndef __TYPES_H__
#define __TYPES_H__

typedef enum return_type {
  RETURN_NONE,
  RETURN_EXIT,
  RETURN_ERROR_OPT_UNKNOWN,
  RETURN_ERROR_OPT_MISSING_ARG,
  RETURN_ERROR_OPT_ARGUMENT,
  RETURN_ERROR_CAPACITY,
  RETURN_ERROR_UNACCESSIBLE_FILE,
  RETURN_ERROR_IO,
} return_type;

#endif
